"""empty message

Revision ID: d70ae9315d46
Revises: 718bb7efd2b1
Create Date: 2021-08-05 02:19:20.990841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70ae9315d46'
down_revision = '718bb7efd2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
